// Import the global styles
import "./globals.css";
// Import your custom components
// Import the Roboto font from 'next/font/google'
import { Roboto, Lora } from "@next/font/google";

// Define the font using the Roboto function
const roboto = Roboto({
  weight: "400",
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

const lora = Lora({
  weight: "400",
  style: "normal",
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* Ensure to include the <Head> component from Next.js */}</head>
      <body className={`${roboto.className} ${lora.className} bg-white`}>
        {children}
      </body>
    </html>
  );
}
